import React, { useEffect, useState } from 'react';
import { User } from '../../models/User';
import { ValidationAggregate, ValidationScenario } from '../../models';
import { validationLabRepository } from '../../repositories';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { UnauthorizedState } from '../../components/ui/RouteStates';
import { getErrorMessage } from '../../utils/errors';
import { calculateValidationMetrics, UTM_PILOT_SERVICE } from '../../utils/validationLab';
import { getJalaliYear } from '../../utils/jalaliDate';

const DISCLAIMER = 'این بخش برای ارزیابی و کالیبراسیون آزمایشی است و تعرفه رسمی تولید نمی‌کند.';
const initialForm = () => ({parcelAreaM2:'',boundaryVertexCount:'',regionClass:'metropolitan',accessLevel:'standard',fieldCondition:'normal',complexityLevel:'standard',urgencyLevel:'normal',expertMinimumPrice:'',expertExpectedPrice:'',expertMaximumPrice:'',actualAgreedPrice:'',executionYear:String(getJalaliYear())});

export const ValidationLabView:React.FC<{user:User}> = ({user}) => {
  const actor={userId:user.id,role:user.role,environment:'demo' as const};
  const [items,setItems]=useState<ValidationScenario[]>([]),[aggregate,setAggregate]=useState<ValidationAggregate|null>(null),[message,setMessage]=useState(''),[importText,setImportText]=useState(''),[exportText,setExportText]=useState('');
  const [pending,setPending]=useState(false),[proposalId,setProposalId]=useState(''),[form,setForm]=useState(initialForm);
  const load=async()=>{try{if(user.role==='admin'){setItems(await validationLabRepository.getScenarios(actor));setAggregate(await validationLabRepository.getAggregate(actor,{}));}}catch(e){setMessage(getErrorMessage(e,'بارگذاری آزمایشگاه انجام نشد.'));}};
  useEffect(()=>{void load();},[user.id,user.role]);
  if(user.role!=='admin')return <UnauthorizedState/>;
  const submit=async()=>{if(pending)return;setPending(true);setMessage('');try{const area=Number(form.parcelAreaM2);const saved=await validationLabRepository.createScenario(actor,{serviceId:UTM_PILOT_SERVICE.id,serviceTitleSnapshot:UTM_PILOT_SERVICE.title,quantity:area,unit:'مترمربع',regionClass:form.regionClass as ValidationScenario['regionClass'],complexityLevel:form.complexityLevel as ValidationScenario['complexityLevel'],urgencyLevel:form.urgencyLevel as ValidationScenario['urgencyLevel'],parcelAreaM2:area,boundaryVertexCount:Number(form.boundaryVertexCount),accessLevel:form.accessLevel as ValidationScenario['accessLevel'],fieldCondition:form.fieldCondition as ValidationScenario['fieldCondition'],executionYear:Number(form.executionYear),environmentalFactors:[],equipmentFactors:[],reasonCodes:['expert_judgment'],executionDate:`${form.executionYear}/01/01`,expertMinimumPrice:Number(form.expertMinimumPrice),expertExpectedPrice:Number(form.expertExpectedPrice),expertMaximumPrice:Number(form.expertMaximumPrice),actualAgreedPrice:form.actualAgreedPrice.trim()===''?undefined:Number(form.actualAgreedPrice),expertCount:1,expertConfidence:'medium',sourceType:'completed_work'});setMessage(saved.calculationStatus==='unavailable'?'برآورد موتور برای این خدمت در دسترس نیست؛ ابتدا تعرفه نسخه‌دار آن تعریف شود.':'سناریوی ناشناس ذخیره شد.');setForm(initialForm());await load();}catch(e){setMessage(getErrorMessage(e,'سناریو ذخیره نشد.'));}finally{setPending(false);}};
  const exportData=async()=>{try{setExportText(JSON.stringify(await validationLabRepository.exportDemo(actor),null,2));setMessage('خروجی امن آماده شد.');}catch(e){setMessage(getErrorMessage(e,'Export انجام نشد.'));}};
  const importData=async()=>{try{const n=await validationLabRepository.importDemo(actor,importText);setMessage(`${n} سناریو به‌صورت اتمیک Import شد.`);await load();}catch(e){setMessage(getErrorMessage(e,'Import انجام نشد.'));}};
  const createProposal=async()=>{try{const proposal=await validationLabRepository.createCalibrationSuggestion(actor,'all',{});if(!proposal){setMessage('نمونه معتبر برای ایجاد پیشنهاد کالیبراسیون کافی نیست.');return;}setProposalId(proposal.id);setMessage('پیشنهاد کالیبراسیون برای بررسی مدیر ایجاد شد؛ هیچ تغییری خودکار اعمال نشد.');}catch(e){setMessage(getErrorMessage(e,'پیشنهاد ایجاد نشد.'));}};
  const reviewProposal=async()=>{try{await validationLabRepository.versionProposal(actor,proposalId);setMessage('بررسی مدیر به‌صورت نسخه جدید و immutable ثبت شد.');}catch(e){setMessage(getErrorMessage(e,'بررسی پیشنهاد ثبت نشد.'));}};
  const select=(label:string,key:keyof ReturnType<typeof initialForm>,options:Array<[string,string]>)=><label className="text-xs font-bold">{label}<select className="block w-full mt-1 p-3 border rounded-xl" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}>{options.map(([value,title])=><option key={value} value={value}>{title}</option>)}</select></label>;
  const amount=(label:string,key:'expertMinimumPrice'|'expertExpectedPrice'|'expertMaximumPrice'|'actualAgreedPrice')=><Input label={`${label} (تومان)${key==='actualAgreedPrice'?' — اختیاری':''}`} type="number" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>;
  return <section className="space-y-5" dir="rtl"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><h2 className="font-black text-lg">آزمایشگاه اعتبارسنجی و کالیبراسیون</h2><p className="text-sm text-amber-900 mt-1">{DISCLAIMER}</p></div>{message&&<p role="status" aria-live="polite" className="p-3 rounded-xl bg-slate-100 text-sm">{message}</p>}
  <><form className="bg-white border rounded-2xl p-4 space-y-4" onSubmit={e=>{e.preventDefault();void submit();}}><h3 className="font-bold">ثبت سناریوی ناشناس UTM سند تک‌برگ</h3><p className="text-sm text-slate-600">خدمت: {UTM_PILOT_SERVICE.title}</p><div className="grid sm:grid-cols-3 gap-3">
    <Input label="مساحت ملک (مترمربع)" type="number" value={form.parcelAreaM2} onChange={e=>setForm({...form,parcelAreaM2:e.target.value})}/><Input label="تعداد تقریبی شکست‌ها" type="number" step="any" value={form.boundaryVertexCount} onChange={e=>setForm({...form,boundaryVertexCount:e.target.value})}/><Input label="سال انجام (شمسی)" type="number" step="any" value={form.executionYear} onChange={e=>setForm({...form,executionYear:e.target.value})}/>
    {select('نوع منطقه','regionClass',[['metropolitan','کلان‌شهر'],['provincial_capital','مرکز استان'],['other_urban','سایر شهرها'],['rural','روستایی']])}{select('دسترسی','accessLevel',[['easy','آسان'],['standard','معمولی'],['difficult','دشوار']])}{select('شرایط برداشت','fieldCondition',[['normal','عادی'],['difficult','دشوار']])}{select('پیچیدگی','complexityLevel',[['low','کم'],['standard','معمولی'],['high','زیاد'],['exceptional','ویژه']])}{select('فوریت','urgencyLevel',[['normal','عادی'],['urgent','فوری'],['critical','بحرانی']])}
    {amount('حداقل قیمت کارشناسی','expertMinimumPrice')}{amount('قیمت مورد انتظار','expertExpectedPrice')}{amount('حداکثر قیمت کارشناسی','expertMaximumPrice')}{amount('قیمت توافق‌شده','actualAgreedPrice')}
    </div><p className="text-xs text-slate-500">این اطلاعات فقط metadata اعتبارسنجی‌اند و هیچ ضریب یا تغییر قیمت خودکار ایجاد نمی‌کنند.</p><Button type="submit" isLoading={pending} disabled={pending}>ذخیره سناریوی ناشناس</Button></form>
    <div className="bg-white border rounded-2xl p-4"><h3 className="font-bold mb-3">سناریوهای ناشناس</h3>{items.length===0?<p className="text-sm text-slate-500">سناریویی ثبت نشده است.</p>:items.map(s=>{const m=s.calculationStatus==='calculated'?calculateValidationMetrics(s):null;return <article key={s.scenarioId} className="border-b py-3 text-sm"><b>{s.serviceTitleSnapshot}</b> — مساحت: {s.parcelAreaM2?.toLocaleString('fa-IR')} مترمربع — {s.calculationStatus==='invalid_legacy_calculation'?'این سناریو با نسخه آزمایشی قبلی محاسبه شده و باید دوباره ثبت شود.':m?<>خطای مطلق: {m.absoluteError.toLocaleString('fa-IR')} تومان — {m.withinExpertRange?'داخل بازه':'خارج بازه'}</>:'برآورد موتور برای این خدمت در دسترس نیست؛ ابتدا تعرفه نسخه‌دار آن تعریف شود.'}</article>;})}</div>
    <div className="bg-white border rounded-2xl p-4"><h3 className="font-bold">داشبورد تجمیعی مدیر</h3>{aggregate?.suppressed?<p className="mt-2 text-amber-700">نمونه ناکافی؛ تمام شاخص‌ها پنهان هستند. (n={aggregate.sampleCount})</p>:<p className="mt-2">MdAPE: {aggregate?.medianAbsolutePercentageError}% — داخل بازه: {aggregate?.withinExpertRangePercent}%</p>}</div><div className="bg-white border rounded-2xl p-4 space-y-3"><h3 className="font-bold">پیشنهادهای کالیبراسیون و Import/Export امن</h3><p className="text-xs text-slate-600">هیچ پیشنهاد یا ضریبی خودکار اعمال نمی‌شود؛ نسخه جدید فقط پس از بررسی مدیر ساخته می‌شود.</p><div className="flex flex-wrap gap-2"><Button onClick={()=>void createProposal()}>ایجاد پیشنهاد کالیبراسیون</Button>{proposalId&&<Button variant="outline" onClick={()=>void reviewProposal()}>ثبت بررسی در نسخه جدید</Button>}<Button onClick={()=>void exportData()}>Export امن</Button><Button variant="outline" onClick={()=>void importData()}>Import اتمیک</Button></div><textarea aria-label="JSON ورودی" className="w-full min-h-28 p-3 border rounded-xl" value={importText} onChange={e=>setImportText(e.target.value)}/>{exportText&&<pre className="max-h-56 overflow-auto text-left text-xs bg-slate-900 text-slate-100 p-3 rounded-xl" dir="ltr">{exportText}</pre>}</div></>
  </section>;
};
export default ValidationLabView;
