import React from 'react';
import { FolderPlus, ListTree, Coins, Calculator, SlidersHorizontal, FileText, FileSignature, ReceiptText, WalletCards, Archive, UserRound, GraduationCap, BadgeCheck, Images, Star, Settings, Users, ShieldCheck, MessageSquareWarning, ScrollText, FlaskConical, Upload, Palette, ToggleLeft, DatabaseBackup, Info, Search, Send, GitCompareArrows, CheckCircle2 } from 'lucide-react';
import { HubCard, HubSection, PageHeader } from '../../components/hub';
import { AppTheme } from '../../utils/theme';

export const ProjectHub:React.FC<{open:(view:'create'|'manage')=>void}>=({open})=><div className="hub-page"><PageHeader title="مرکز پروژه‌ها" description="ثبت مرحله‌ای پروژه یا مدیریت پرونده‌های موجود"/><HubSection title="عملیات پروژه"><HubCard icon={FolderPlus} title="ثبت پروژه" description="فرم مرحله‌ای، ذخیره خودکار و ادامه آخرین پیش‌نویس" badge="۶ مرحله" onClick={()=>open('create')}/><HubCard icon={ListTree} title="مدیریت پروژه‌ها" description="فعال، پیش‌نویس، تکمیل‌شده، حذف‌شده، جست‌وجو و فیلتر" onClick={()=>open('manage')}/></HubSection></div>;

export const PricingHub:React.FC<{open:(view:string)=>void}>=({open})=><div className="hub-page"><PageHeader title="مرکز قیمت‌گذاری" description="جریان چهارمرحله‌ای برآورد، هزینه داخلی و مقایسه منابع"/><HubSection title="ابزارهای قیمت"><HubCard icon={Calculator} title="۱. برآورد اولیه قیمت" description="حجم تقریبی، تعرفه نسخه‌دار یا بازار معتبر؛ بدون هزینه شخصی" onClick={()=>open('estimate')}/><HubCard icon={Coins} title="۲. نرخ‌های هزینه شخصی" description="اطلاعات داخلی و محرمانه نیروی انسانی، تجهیزات و هزینه‌های جانبی" onClick={()=>open('rates')}/><HubCard icon={WalletCards} title="۳. محاسبه قیمت واقعی پروژه" description="هزینه مستقیم، سربار، کف قیمت و سه سطح متصل به پروژه" onClick={()=>open('costs')}/><HubCard icon={FileText} title="۴. تعرفه‌ها و قیمت‌های منتشرشده" description="نمایش مبلغ، واحد، نسخه، سال، منبع و شاخص معتبر بازار" onClick={()=>open('published')}/></HubSection></div>;

export const DocumentsLandingHub:React.FC<{open:()=>void}>=({open})=><div className="hub-page"><PageHeader title="مرکز اسناد" description="هر گروه سند در کارتابل مستقل پروژه مدیریت می‌شود"/><HubSection title="اسناد و دریافت‌ها">{[[FileText,'پیش‌فاکتورها'],[FileSignature,'قراردادها'],[ReceiptText,'صورت‌وضعیت‌ها'],[WalletCards,'صورت‌حساب‌ها'],[Coins,'برنامه پرداخت'],[BadgeCheck,'اسناد صادرشده'],[Archive,'بایگانی']].map(([icon,title])=><HubCard key={String(title)} icon={icon as typeof FileText} title={String(title)} description="انتخاب پروژه و ورود به صفحه مستقل این بخش" onClick={open}/>)}</HubSection></div>;

export const ProfileHub:React.FC<{open:()=>void}>=({open})=><div className="hub-page"><PageHeader title="مرکز پروفایل حرفه‌ای" description="مدیریت اطلاعات عمومی، سوابق و تنظیمات حساب"/><HubSection title="پروفایل و انتشار">{[[UserRound,'مشخصات عمومی و حرفه‌ای'],[GraduationCap,'سوابق کاری و تحصیلی'],[BadgeCheck,'پروانه‌ها و مدارک'],[Images,'نمونه‌کارها'],[Coins,'تعرفه‌های منتشرشده'],[Star,'نظرات و امتیازها'],[Settings,'تنظیمات حساب و ظاهر']].map(([icon,title])=><HubCard key={String(title)} icon={icon as typeof UserRound} title={String(title)} description="ورود به بخش تخصصی پروفایل" onClick={open}/>)}</HubSection></div>;

export const ClientHomeHub:React.FC<{open:(view:string)=>void}>=({open})=><div className="hub-page"><PageHeader title="داشبورد کارفرما" description="خلاصه درخواست‌ها، انتخاب‌های اخیر و اقدام بعدی"/><HubSection title="دسترسی سریع"><HubCard icon={Search} title="یافتن نقشه‌بردار" description="جست‌وجو و بررسی پروفایل‌های عمومی" onClick={()=>open('client_surveyors')}/><HubCard icon={Send} title="درخواست‌های من" description="پیگیری وضعیت استعلام و اطلاعات تماس مجاز" onClick={()=>open('client_requests')}/><HubCard icon={CheckCircle2} title="همکاری‌های تکمیل‌شده" description="ثبت نظر فقط برای همکاری مجاز" onClick={()=>open('client_requests')}/></HubSection></div>;

export const ClientPricesHub:React.FC<{open:()=>void}>=({open})=><div className="hub-page"><PageHeader title="مرکز قیمت‌های عمومی" description="قیمت‌ها نمایشی‌اند و تعرفه رسمی یا قانونی محسوب نمی‌شوند"/><HubSection title="قیمت‌ها"><HubCard icon={Coins} title="تعرفه‌های عمومی منتشرشده" description="بدون افشای هزینه واقعی، سود یا نرخ شخصی" onClick={open}/><HubCard icon={GitCompareArrows} title="مقایسه خدمات" description="مقایسه کارت‌های قیمت منتشرشده" onClick={open}/></HubSection></div>;

export const AdminHub:React.FC<{kind:'management'|'tariffs'|'settings';open:(view:string)=>void;theme:AppTheme;setTheme:(t:AppTheme)=>void}>=({kind,open,theme,setTheme})=>{const definitions=kind==='management'?[[Users,'کاربران و نقش‌ها'],[ShieldCheck,'بررسی نمایشی مدارک'],[MessageSquareWarning,'نظارت بر نظرات'],[BadgeCheck,'دسترسی‌ها'],[ScrollText,'گزارش رویدادها']]:kind==='tariffs'?[[ListTree,'کاتالوگ خدمات'],[Coins,'نسخه‌های تعرفه'],[SlidersHorizontal,'تنظیمات قیمت‌گذاری'],[ToggleLeft,'فعال‌سازی نسخه'],[Archive,'تاریخچه immutable']]:[[Palette,'ظاهر و تم'],[ToggleLeft,'feature flags'],[DatabaseBackup,'ابزارهای Demo'],[Upload,'Export / Reset'],[Info,'درباره نسخه']];return <div className="hub-page"><PageHeader title={kind==='management'?'مرکز مدیریت':kind==='tariffs'?'مرکز تعرفه‌ها':'تنظیمات سامانه'} description="دسترسی مدیریتی کنترل‌شده و بدون ایجاد مجوز کسب‌وکاری جدید"/>{kind==='settings'&&<div className="theme-switcher" role="group" aria-label="انتخاب تم">{(['light','dark','system'] as AppTheme[]).map(t=><button key={t} aria-pressed={theme===t} onClick={()=>setTheme(t)}>{t==='light'?'روشن':t==='dark'?'تیره':'سیستم'}</button>)}</div>}<HubSection title="بخش‌ها">{definitions.map(([icon,title])=><HubCard key={String(title)} icon={icon as typeof Users} title={String(title)} description="ورود به صفحه مدیریتی مستقل" onClick={()=>open(kind==='management'?'moderation':'pricing')}/>)}</HubSection></div>};

export const LabHub:React.FC<{open:()=>void}>=({open})=><div className="hub-page"><PageHeader title="مرکز آزمایشگاه اعتبارسنجی" description="فقط مدیر و براساس feature flag موجود"/><HubSection title="ابزارها"><HubCard icon={FlaskConical} title="ثبت سناریو و گزارش تجمیعی" description="Import/Export امن و پیشنهادهای کالیبراسیون" onClick={open}/></HubSection></div>;
