import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { DemoValidationLabRepository } from '../repositories/demo';
import { RepositoryActor } from '../models/Stage6Models';
import { UTM_PILOT_SERVICE } from './validationLab';
import { getJalaliYear } from './jalaliDate';

type Result={title:string;passed:boolean;message:string};
const admin:RepositoryActor={userId:'admin-lab',role:'admin',environment:'demo'},surveyor:RepositoryActor={userId:'surveyor-lab',role:'surveyor',environment:'demo'},client:RepositoryActor={userId:'client-lab',role:'client',environment:'demo'};
const input=()=>({serviceId:UTM_PILOT_SERVICE.id,serviceTitleSnapshot:UTM_PILOT_SERVICE.title,quantity:500,unit:'مترمربع' as const,regionClass:'metropolitan' as const,complexityLevel:'standard' as const,urgencyLevel:'normal' as const,parcelAreaM2:500,boundaryVertexCount:4,accessLevel:'standard' as const,fieldCondition:'normal' as const,executionYear:getJalaliYear(),environmentalFactors:[],equipmentFactors:[],reasonCodes:['expert_judgment' as const],executionDate:`${getJalaliYear()}/01/01`,expertMinimumPrice:4_000_000,expertExpectedPrice:5_000_000,expertMaximumPrice:6_000_000,actualAgreedPrice:9_000_000,expertCount:1,expertConfidence:'medium' as const,sourceType:'completed_work' as const});
const rejects=async(fn:()=>Promise<unknown>)=>{try{await fn();return false;}catch{return true;}};
export async function runAdminValidationLabTests():Promise<Result[]>{const out:Result[]=[];const test=async(title:string,fn:()=>boolean|Promise<boolean>)=>{try{out.push({title,passed:await fn(),message:'موفق'});}catch(e){out.push({title,passed:false,message:e instanceof Error?e.message:'خطا'});}};
 await test('منوی آزمایشگاه فقط در block مدیر باشد',()=>{const nav=readFileSync(resolve('src/components/layout/BottomNavigation.tsx'),'utf8');return (nav.match(/id: 'validation_lab'/g)||[]).length===1&&nav.indexOf("if (userRole === 'admin')")<nav.indexOf("id: 'validation_lab'");});
 await test('route مستقیم فقط admin باشد',()=>readFileSync(resolve('src/app/App.tsx'),'utf8').includes("activeTab === 'validation_lab' && (currentUser.role === 'admin'"));
 await test('Repository تمام عملیات غیرمدیر را رد کند',async()=>{localStorage.clear();const repo=new DemoValidationLabRepository();return await rejects(()=>repo.createScenario(surveyor,input()))&&await rejects(()=>repo.getScenarios(client))&&await rejects(()=>repo.exportDemo(surveyor));});
 await test('خاموش‌بودن flag همه عملیات را رد کند',async()=>{localStorage.clear();const repo=new DemoValidationLabRepository();await repo.setEnabled(admin,false);const denied=await rejects(()=>repo.createScenario(admin,input()))&&await rejects(()=>repo.getScenarios(admin))&&await rejects(()=>repo.getAggregate(admin,{}));await repo.setEnabled(admin,true);return denied;});
 await test('Real پیش‌فرض خاموش و غیرقابل فعال‌سازی باشد',async()=>{localStorage.clear();const repo=new DemoValidationLabRepository(),real={...admin,environment:'real' as const};return await rejects(()=>repo.getScenarios(real))&&await rejects(()=>repo.setEnabled(real,true));});
 await test('نبود تعرفه UTM unavailable باشد نه copy',async()=>{localStorage.clear();const saved=await new DemoValidationLabRepository().createScenario(admin,input());return saved.calculationStatus==='unavailable'&&saved.engineEstimatedPrice===undefined&&saved.expertExpectedPrice===5_000_000;});
 await test('legacy آلوده از aggregate و n حذف شود',async()=>{localStorage.clear();const dirty={...input(),scenarioId:'dirty',schemaVersion:2,environment:'demo',ownerUserId:'old',expertPseudonym:'old',createdAt:new Date().toISOString(),anonymized:true,currency:'TOMAN',calculationStatus:'calculated',engineEstimatedPrice:5_000_000,engineVersion:'stage9.1',settingsVersion:'pricing-settings.v1',tariffVersion:'snapshot-active'};localStorage.setItem('surveying.validationLab.v2.demo',JSON.stringify([dirty]));const repo=new DemoValidationLabRepository(),all=await repo.getScenarios(admin),aggregate=await repo.getAggregate(admin,{});return all[0].calculationStatus==='invalid_legacy_calculation'&&aggregate.sampleCount===0&&aggregate.suppressed;});
 await test('Import خروجی موتور و snapshot جعلی را رد کند',async()=>{localStorage.clear();const repo=new DemoValidationLabRepository(),payload={schemaVersion:2,environment:'demo',exportedAt:'',scenarios:[{...input(),scenarioId:'fake',schemaVersion:2,environment:'demo',createdAt:'',anonymized:true,currency:'TOMAN',engineEstimatedPrice:1,engineVersion:'fake'}]};return rejects(()=>repo.importDemo(admin,JSON.stringify(payload)));});
 return out;}
