import { DEFAULT_PRICING_SETTINGS, DEFAULT_SERVICE_CATEGORIES, DEFAULT_SURVEYING_SERVICES, MarketPriceRecord, ProjectCostEstimate } from '../models';
import { DemoMarketPricesRepository } from '../repositories/demo/DemoMarketPricesRepository';
import { DemoTariffsRepository } from '../repositories/demo/DemoTariffsRepository';
import { DemoProjectRepository } from '../repositories/demo/DemoProjectRepository';
import { DemoProjectCostsRepository } from '../repositories/demo/DemoProjectCostsRepository';
import { DemoPersonalRatesRepository } from '../repositories/demo/DemoPersonalRatesRepository';
import { buildEmployerPriceSummary, calculateProjectPricing, getMarketStatisticsForService } from './pricingEngine';
import { canEditPricing, canViewTariffs } from './pricingAccess';

type Result={testNumber:number;title:string;passed:boolean;message:string};
const memory=new Map<string,string>();
const localStorageMock={getItem:(k:string)=>memory.get(k)??null,setItem:(k:string,v:string)=>void memory.set(k,String(v)),removeItem:(k:string)=>void memory.delete(k),clear:()=>memory.clear(),key:(i:number)=>[...memory.keys()][i]??null,get length(){return memory.size;}};
Object.defineProperty(globalThis,'localStorage',{value:localStorageMock,configurable:true});
const record=(id:string,isDemo:boolean,unitPrice:number):MarketPriceRecord=>({id,serviceId:'sur_1',serviceTitle:'برداشت',projectId:`p_${id}`,userId:'u',unit:'بلوک',unitPrice,totalPrice:unitPrice,quantity:1,reliabilityWeight:1,isDemo,isOutlier:false,projectStatus:'completed',createdAt:'',updatedAt:''});

export async function runStage4IntegrationTests(){
 const out:Result[]=[]; const test=async(n:number,title:string,fn:()=>boolean|Promise<boolean>)=>{try{const ok=await fn();out.push({testNumber:n,title,passed:ok,message:ok?'موفق':'شرط آزمون برقرار نشد'});}catch(e){out.push({testNumber:n,title,passed:false,message:e instanceof Error?e.message:String(e)});}};
 await test(21,'نقشه‌بردار نتواند تعرفه را ویرایش کند',()=>!canEditPricing('surveyor'));
 await test(22,'کارفرما نتواند صفحه مدیر را باز کند',()=>!canViewTariffs('client'));
 await test(23,'مدیر بتواند تعرفه را ویرایش کند',async()=>{memory.clear();const updated=await new DemoTariffsRepository().updateTariff('sur_1',{baseRate:4_600_000,minAmount:3_000_000,version:'1405.1',validFrom:'1405/01/01',sourceTitle:'آزمون مدیر'},{id:'a',name:'مدیر',role:'admin'});return canEditPricing('admin')&&updated.baseRate===4_600_000;});
 await test(24,'Repository ویرایش غیرمدیر را رد کند',async()=>{memory.clear();try{await new DemoTariffsRepository().updateTariff('sur_1',{baseRate:1,minAmount:1,version:'x',validFrom:'1405/01/01',sourceTitle:'x'},{id:'s',name:'نقشه‌بردار',role:'surveyor'});return false;}catch{return true;}});
 await test(25,'Demo و واقعی هرگز ترکیب نشوند',async()=>{memory.clear();localStorageMock.setItem('surveying.marketPrices.v1',JSON.stringify([record('d',true,10),record('r',false,20)]));const repo=new DemoMarketPricesRepository();const d=await repo.getMarketRecords('sur_1','demo');const r=await repo.getMarketRecords('sur_1','real');return d.length===1&&r.length===1&&d.every(x=>x.isDemo)&&r.every(x=>!x.isDemo);});
 await test(26,'حالت real نمونه Demo را در sampleCount حساب نکند',async()=>{const s=await new DemoMarketPricesRepository().getMarketStatistics('sur_1','real');return s.totalSamples===1&&s.validSamples===1;});
 await test(27,'مقدار ۰٫۱ نرخ واحد ۴۶ میلیون را به کل ۴٫۶ میلیون تبدیل کند',()=>{const stats=getMarketStatisticsForService(Array.from({length:6},(_,i)=>record(String(i),true,46_000_000)),'sur_1',DEFAULT_PRICING_SETTINGS);const r=calculateProjectPricing({actualCost:0,quantity:.1,unit:'بلوک',baseRate:1,minAmount:1,locationCoefficient:1,difficultyCoefficient:1,riskCoefficient:1,qualityCoefficient:1,profitPercent:0,taxesAndDeductions:0,selectedLevel:'standard'},stats,DEFAULT_PRICING_SETTINGS);return r.marketMedian===46_000_000&&r.marketTotalMedian===4_600_000;});
 await test(28,'مقدار ۱۰ قیمت استاندارد ۴۵٫۴ میلیون بسازد',()=>{const stats=getMarketStatisticsForService(Array.from({length:6},(_,i)=>record(String(i),true,4_600_000)),'sur_1',DEFAULT_PRICING_SETTINGS);const r=calculateProjectPricing({actualCost:27_580_000,quantity:10,unit:'بلوک',baseRate:4_500_000,minAmount:3_000_000,locationCoefficient:1,difficultyCoefficient:1,riskCoefficient:1,qualityCoefficient:1,profitPercent:20,taxesAndDeductions:0,selectedLevel:'standard'},stats,DEFAULT_PRICING_SETTINGS);return r.referencePrice===45_400_000&&r.standardPrice===45_400_000&&r.finalPrice===45_400_000;});
 await test(29,'برچسب بازار براساس میانه کل باشد',()=>{const stats=getMarketStatisticsForService(Array.from({length:6},(_,i)=>record(String(i),true,4_600_000)),'sur_1',DEFAULT_PRICING_SETTINGS);const r=calculateProjectPricing({actualCost:27_580_000,quantity:10,unit:'بلوک',baseRate:4_500_000,minAmount:3_000_000,locationCoefficient:1,difficultyCoefficient:1,riskCoefficient:1,qualityCoefficient:1,profitPercent:20,taxesAndDeductions:0,selectedLevel:'standard'},stats,DEFAULT_PRICING_SETTINGS);return r.marketTotalMedian===46_000_000&&r.comparisonLabel==='within_market';});
 await test(30,'گروه و پنج خدمت پایه با افزودن ریزخدمات جدید حفظ شوند',()=>DEFAULT_SERVICE_CATEGORIES.length===1&&['sur_1','sur_2','sur_3','sur_4','sur_5'].every(id=>DEFAULT_SURVEYING_SERVICES.some(s=>s.id===id)));
 await test(31,'بازگشت ثبت پروژه و سال تاریخ شمسی',async()=>{memory.clear();const repo=new DemoProjectRepository();const before=(await repo.getProjects('u2')).length;await repo.createDraft('u2');const after=(await repo.getProjects('u2')).length;return before===after&&repo.generateProjectCode('u2','1405/07/01').startsWith('PRJ-1405-');});
 await test(32,'بازگشت نرخ‌های شخصی، هزینه پروژه و استهلاک تجهیز',async()=>{memory.clear();const rates=await new DemoPersonalRatesRepository().getPersonalRates('u');const repo=new DemoProjectCostsRepository();const cost:ProjectCostEstimate={id:'c',userId:'u',projectId:'p',items:[{id:'o',category:'equipment',title:'توتال',quantity:1,unit:'روز',unitRate:100,calculatedAmount:120,finalAmount:120,isManuallyEdited:false,equipmentOwnership:'owned',depreciationAmount:20},{id:'r',category:'equipment',title:'اجاره',quantity:1,unit:'روز',unitRate:100,calculatedAmount:100,finalAmount:100,isManuallyEdited:false,equipmentOwnership:'rented',depreciationAmount:50}],officeCost:{totalAmount:0},updatedAt:'',environment:'demo',currency:'TOMAN',schemaVersion:1};const saved=await repo.saveProjectCost(cost);return rates.laborRates.length===3&&saved.items[0].depreciationAmount===20&&saved.items[1].depreciationAmount===0;});
 await test(33,'Preview هزینه، سود و نرخ شخصی را افشا نکند',()=>{const stats=getMarketStatisticsForService(Array.from({length:6},(_,i)=>record(String(i),true,100)),'sur_1',DEFAULT_PRICING_SETTINGS);const calc=calculateProjectPricing({actualCost:100,quantity:1,unit:'بلوک',baseRate:100,minAmount:100,locationCoefficient:1,difficultyCoefficient:1,riskCoefficient:1,qualityCoefficient:1,profitPercent:20,taxesAndDeductions:0,selectedLevel:'standard'},stats,DEFAULT_PRICING_SETTINGS);const summary=buildEmployerPriceSummary('p','s',calc);const text=JSON.stringify(summary);return !['actualCost','profitPercent','personalRates','depreciation'].some(k=>text.includes(k));});
 return {total:out.length,passed:out.filter(x=>x.passed).length,failed:out.filter(x=>!x.passed).length,results:out};
}
